package backend.camp.dto;

import backend.camp.CampParticipant;
import backend.camp.CampReward;
import backend.camp.CampStatus;
import backend.camp.Instructor;
import backend.camp.ScheduleDay;
import backend.camp.TrainingPillar;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.util.List;

/**
 * Payload to create a new camp. Created as a hidden DRAFT — the slug is
 * generated by the service from {@code name} + {@code year}, and
 * {@code published} is always forced to {@code false} on create (there is no
 * field for it here).
 *
 * <p>Only {@code name} and {@code year} are strictly required (they drive slug
 * generation); everything else is optional so an admin can save a skeleton and
 * flesh it out via edits. Nested lists reuse the entity's Lombok classes, which
 * Jackson can bind directly from JSON.
 */
public record CampCreateRequest(

        @NotBlank(message = "Camp name is required")
        String name,

        String subtitle,
        String location,
        String state,

        @NotNull(message = "Year is required")
        Integer year,

        String duration,
        Integer participants,
        Integer sessions,
        Integer instructorCount,
        String heroImage,
        List<String> aboutImages,
        String quote,
        String quoteAuthor,
        String description,
        String kana,
        List<TrainingPillar> pillars,
        List<Instructor> instructors,
        List<ScheduleDay> schedule,
        List<String> galleryImages,

        /** Results roster (participant rows + placement + user-link). Optional. */
        List<CampParticipant> results,

        /** Per-placement prizes (rank → cosmetic id). Optional. */
        List<CampReward> rewards,

        /** Stored status; defaults to UPCOMING when omitted (see service). */
        CampStatus status
) {
}
