spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  forward-headers-strategy: framework

app:
  security:
    csrf-enabled: true
  cookies:
    secure: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.hibernate.SQL: WARN
