package backend.event.dto;

import backend.event.EventType;
import backend.event.EventReward;
import backend.event.Participant;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.util.List;

/**
 * Payload to create a new event. Created as a hidden DRAFT — the slug is
 * generated by the service, {@code published} is forced to {@code false}, and
 * for a SUB_ADMIN the {@code state} is overridden with their managed state
 * regardless of what is sent here (see {@link backend.event.EventServiceImpl}).
 *
 * <p>{@code eventDate} drives the derived upcoming/past status. Nested
 * {@code participants} reuse the entity's Lombok class (Jackson-bindable) and are
 * typically only supplied for past events with results.
 */
public record EventCreateRequest(

        @NotBlank(message = "Title is required")
        String title,

        @NotNull(message = "Event date is required")
        LocalDate eventDate,

        @NotBlank(message = "Location is required")
        String location,

        @NotBlank(message = "Organizer is required")
        String organizer,

        @NotNull(message = "Event type is required")
        EventType type,

        String prizePool,
        String duration,
        Integer totalParticipants,
        String highlight,

        /** Venue state. Honoured for ADMIN; overridden by managed state for SUB_ADMIN. */
        @NotBlank(message = "State is required")
        String state,

        List<Participant> participants,

        /** Per-placement prizes (rank → cosmetic id). Optional. */
        List<EventReward> rewards
) {
}
